const ServerError = require('./ServerError');

const BAD_REQUEST = 'BAD_REQUEST';
const INVALID_EMAIL = 'INVALID_EMAIL';
const UNREGISTERED_STUDENT = 'UNREGISTERED_STUDENT';
const UNREGISTERED_TEACHER = 'UNREGISTERED_TEACHER';

module.exports = {
  ServerError,
  BAD_REQUEST,
  INVALID_EMAIL,
  UNREGISTERED_STUDENT,
  UNREGISTERED_TEACHER,
};
